'use strict';


import { observable, action} from 'mobx';

export type InstrTrack = {
    id: number,
    name: string,
    filename: string,
    muted: boolean,
};

export type music = {
    name: string,
    scoreimage: string,
    tracks:InstrTrack[],
    duration:number,
    bpm:number
};




var initialStore = [
    {
        name: "Yehudi Menuhin",
        level: 1,
        positioninlevel: 1,
        path: "yehudi_menuhin",
        author: "",
        scoreimagesize:9715.76,
        totalstartingperiod:11.2,
        duration:198,
        bpm:85,
        marks:[
              {letter:"1", name:"1ª volta",elapsedtime:34, color:"rgba(120,120,120,1)"},
              {letter:"2", name:"2ª volta",elapsedtime:58, color:"rgba(120,120,120,1)"},
              {letter:"3", name:"3ª volta",elapsedtime:80, color:"rgba(120,120,120,1)"},
              {letter:"4", name:"4ª volta",elapsedtime:103, color:"rgba(120,120,120,1)"},
              {letter:"5", name:"5ª volta",elapsedtime:125, color:"rgba(120,120,120,1)"},
              {letter:"6", name:"6ª volta",elapsedtime:153, color:"rgba(120,120,120,1)"},
              {letter:"7", name:"7ª volta",elapsedtime:175, color:"rgba(120,120,120,1)"},
              {letter:"8", name:"8ª volta",elapsedtime:191, color:"rgba(120,120,120,1)"}
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"voz.png",
                filename:"yehudi_menuhin_voz",
                scoreimage: "YehudiMenuhin.svg",
            },
            {
                id:2,
                name:"",
                trackimg:"cd.svg",
                filename:"yehudi_menuhin_instrumental",
                scoreimage:"instrumental_branco.png"
            },
        ],
    },
    {
        name: "Esta cantiga quer viajar",
        level: 1,
        positioninlevel: 2,
        path: "esta_cantiga_quer_viajar",
        author: "",
        scoreimagesize:5300,
        totalstartingperiod:8.2,
        duration:91.5,
        bpm:120,
        marks:[
            {letter:"1", name:"1ª volta",elapsedtime:25, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:41, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:57, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:73, color:"rgba(120,120,120,1)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg: "voz.png",
                filename:"esta_cantiga_quer_viajar_rui-coro",
                scoreimage: "2_Estacantigaquerviajar_1.svg",
            },
            {
                id:2,
                name:"",
                trackimg: "xilofone.png",
                filename:"esta_cantiga_quer_viajar_xilofone",
                scoreimage: "2_Estacantigaquerviajar_2.svg",
            },
            {
                id:3,
                name:"",
                trackimg: "bateria.png",
                filename:"esta_cantiga_quer_viajar_tamborim",
                scoreimage: "2_Estacantigaquerviajar_4.svg",
            },
            {
                id:4,
                name:"",
                trackimg: "clavas.svg",
                filename:"esta_cantiga_quer_viajar_clavas",
                scoreimage: "2_Estacantigaquerviajar_3.svg",
            },
            {
                id:5,
                name:"",
                trackimg: "cd.svg",
                filename:"esta_cantiga_quer_viajar_instrumental",
                scoreimage: "instrumental_branco.png",
            },

        ],
    },
    {
        name: "The lazy song",
        level: 1,
        positioninlevel: 3,
        path: "the_lazy_song",
        author: "",
        scoreimagesize:4513.011,
        totalstartingperiod:3,
        duration:87,
        bpm:175,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:26, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:53, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:75, color:"rgba(120,120,120,1)"}
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"bateria.png",
                scoreimage: "5_Lazysong_1.svg",
                filename:"the_lazy_song_tamborim",
            },
            {
                id:2,
                name:"",
                trackimg:"pandeireta.png",
                scoreimage: "5_Lazysong_2.svg",
                filename:"the_lazy_song_pandeireta",
            },
            {
                id:3,
                name:"",
                trackimg:"clavas.svg",
                scoreimage: "5_Lazysong_3.svg",
                filename:"the_lazy_song_clavas",
            },
            {
                id:4,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "instrumental_branco.png",
                filename:"the_lazy_song_instrumental",
            },
        ],
    },
    {
        name: "All about that bass",
        level: 1,
        positioninlevel: 4,
        path: "all_about_that_bass",
        author: "",
        scoreimagesize:4700,
        totalstartingperiod:1,
        duration:74.5,
        bpm:134,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:15, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:43, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"palmas.svg",
                scoreimage: "6_Allaboutthatbass.svg",
                filename:"All_about_that_bass_estalos_maos_pernas_pes",
            },
            {
                id:2,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "instrumental_branco.png",
                filename:"All_about_that_bass_instrumental",
            },
        ],
    },
    {
        name: "Parabéns a você",
        level: 1,
        positioninlevel: 5,
        path: "parabens_a_voce",
        author: "",
        scoreimagesize:2050,
        totalstartingperiod:7.3,
        duration:41,
        bpm:175,
        marks:[
              {letter:"1", name:"1ª volta",elapsedtime:24, color:"rgba(120,120,120,1)"}
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"flauta.png",
                filename:"Parabens_a_voce_flauta",
                scoreimage: "7_parabensavoce.svg",
            },
            {
                id:2,
                name:"",
                trackimg:"cd.svg",
                filename:"Parabens_a_voce_instrumental",
                scoreimage: "instrumental_branco.png",
            },
        ],
    },
    {
        name: "Asa branca",
        level: 1,
        positioninlevel: 6,
        path: "asa_branca",
        author: "",
        scoreimagesize:4069,
        numberstartingperiods:4,
        totalstartingperiod:7.2,
        duration:80.25,
        bpm:100,
        marks:[
          {letter:"1", name:"1ª volta",elapsedtime:46, color:"rgba(120,120,120,1)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"flauta.png",
                filename:"Asa branca (flauta 100bpm)",
                scoreimage: "8_Asabranca.svg",
            },
            {
                id:2,
                name:"",
                trackimg:"cd.svg",
                filename:"Asa branca (instrumental 100bpm)",
                scoreimage: "instrumental_branco.png",
            },
        ],
    },
    {
        name: "The wayfaring stranger",
        level: 1,
        positioninlevel: 7,
        path: "the_wayfaring_stranger",
        author: "",
        scoreimagesize:3815,
        totalstartingperiod:7.5,
        duration:73,
        bpm:120,
        marks:[
            {letter:"1", name:"1ª volta",elapsedtime:44, color:"rgba(120,120,120,1)"}
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"flauta.png",
                filename:"the_wayfaring_stranger_flauta",
                scoreimage: "9_Thewayfaringstranger.svg",
            },
            {
                id:2,
                name:"",
                trackimg:"cd.svg",
                filename:"the_wayfaring_stranger_instrumental",
                scoreimage: "instrumental_branco.png",
            },
        ],
    },

    {
        name: "Dezembro em Portugal",
        level: 2,
        positioninlevel: 1,
        path: "dezembro_em_portugal",
        author: "",
        scoreimagesize:10195.204,
        totalstartingperiod:5,
        duration:160.5,
        bpm:90,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:27, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:48, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:69.5, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:91, color:"rgba(120,120,120,1)"},
            {letter:"5", name:"5ª volta",elapsedtime:112, color:"rgba(120,120,120,1)"},
            {letter:"6", name:"6ª volta",elapsedtime:133, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"voz.png",
                scoreimage: "dezembro_em_portugal.svg",
                filename:"dezembro_em_portugal_voz",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "dezembro_em_portugal_flauta.svg",
                filename:"dezembro_em_portugal_flauta",
            },
            {
                id:3,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "instrumental_branco.png",
                filename:"dezembro_em_portugal_instrumental",
            },
        ],
    },
    {
        name: "Natal branco",
        level: 2,
        positioninlevel: 2,
        path: "natal_branco",
        author: "",
        scoreimagesize:5367,
        totalstartingperiod:9,
        duration:141,
        bpm:117.6,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:28.9, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:57.8, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:100, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:115.6, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"pandeireta.png",
                scoreimage: "natalbranco_corrido.png",
                filename:"flauta",
            },
            {
                id:2,
                name:"",
                trackimg:"voz.png",
                scoreimage: "natalbranco_corrido.png",
                filename:"silvie",
            },
            {
                id:3,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "instrumental_branco.png",
                filename:"instrumental",
            },
        ],
    },
    {
        name: "Um jardim no peito",
        level: 2,
        positioninlevel: 3,
        path: "um_jardim_no_peito",
        author: "",
        scoreimagesize:7310,
        totalstartingperiod:9.1,
        duration:207,
        bpm:81,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:36, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:47, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:74, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:99, color:"rgba(120,120,120,1)"},
            {letter:"5", name:"5ª volta",elapsedtime:110, color:"rgba(120,120,120,1)"},
            {letter:"6", name:"6ª volta",elapsedtime:134, color:"rgba(120,120,120,1)"},
            {letter:"7", name:"7ª volta",elapsedtime:177, color:"rgba(120,120,120,1)"}
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "um_jardim_no_peito.png",
                filename:"um_jardim_no_peito_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"xilofone.png",
                scoreimage: "um_jardim_no_peito.png",
                filename:"um_jardim_no_peito_voz",
            },
        ],
    },
    {
        name: "Comboio de Belém",
        level: 2,
        positioninlevel: 4,
        path: "comboio_de_belem",
        author: "",
        scoreimagesize:7300,
        totalstartingperiod:10,
        duration:146,
        bpm:90,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:32.5, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:55, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:75, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:98, color:"rgba(120,120,120,1)"},
            {letter:"5", name:"5ª volta",elapsedtime:118, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"Instrumental",
                trackimg:"",
                scoreimage: "comboio_de_belem.png",
                filename:"comboio_de_belem_instrumental",
            },
            {
                id:2,
                name:"cavaquinho",
                trackimg:"cavaquinho.svg",
                scoreimage: "comboio_de_belem.png",
                filename:"comboio_de_belem_cavaquinho",
            },
            {
                id:3,
                name:"",
                trackimg:"voz.png",
                scoreimage: "comboio_de_belem.png",
                filename:"comboio_de_belem_voz",
            },
        ],
    },
    {
        name: "Sleigh ride",
        level: 2,
        positioninlevel: 5,
        path: "sleigh_ride",
        author: "",
        scoreimagesize:3240,
        totalstartingperiod:4.5,
        duration:55,
        bpm:72,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:21.5, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:37, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"palmas.svg",
                scoreimage: "Sleighride_1.png",
                filename:"sleigh_ride_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"palmas.svg",
                scoreimage: "Sleighride_2.png",
                filename:"sleigh_ride_estalos_maoes_pernas",
            },
        ],
    },
    {
        name: "Natal de Elvas",
        level: 2,
        positioninlevel: 6,
        path: "natal_de_elvas",
        author: "",
        scoreimagesize:2900,
        totalstartingperiod:13,
        duration:100,
        bpm:75,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:28.9, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:57.8, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:100, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:115.6, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "NataldeElvas_1.png",
                filename:"natal_de_elvas_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "NataldeElvas_2.png",
                filename:"natal_de_elvas_flauta",
            },
            {
                id:3,
                name:"",
                trackimg:"xilofone.png",
                scoreimage: "NataldeElvas_3.png",
                filename:"natal_de_elvas_xilofone",
            },
        ],
    },
    {
        name: "Entre le boeuf et l'âne gris",
        level: 2,
        positioninlevel: 7,
        path: "entre_le_boeuf_et_l_ane_gris",
        author: "",
        scoreimagesize:3365,
        totalstartingperiod:5,
        duration:73,
        bpm:60,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:27.5, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:48.5, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "Entrelebouef_1.png",
                filename:"entre_le_boeuf_et_l_ane_gris_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "Entrelebouef_2.png",
                filename:"entre_le_boeuf_et_l_ane_gris_flauta",
            },
            {
                id:3,
                name:"",
                trackimg:"xilofone.png",
                scoreimage: "Entrelebouef_3.png",
                filename:"entre_le_boeuf_et_l_ane_gris_xilofone",
            },
            {
                id:4,
                name:"",
                trackimg:"pandeireta.png",
                scoreimage: "Entrelebouef_4.png",
                filename:"entre_le_boeuf_et_l_ane_gris_tamborim",
            },
        ],
    },
    {
        name: "Joy to the World",
        level: 2,
        positioninlevel: 8,
        path: "joy_to_the_world",
        author: "",
        scoreimagesize:3050,
        totalstartingperiod:5.7,
        duration:64,
        bpm:90,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:33, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                trackimg:"cd.svg",
                scoreimage: "Joytotheworld_1.png",
                filename:"joy_to_the_world_instrumental",
            },
            {
                id:2,
                trackimg:"flauta.png",
                scoreimage: "Joytotheworld_2.png",
                filename:"joy_to_the_world_flauta",
            },
            {
                id:3,
                trackimg:"xilofone.png",
                scoreimage: "Joytotheworld_3.png",
                filename:"joy_to_the_world_xilofone",
            },
            {
                id:4,
                trackimg:"cavaquinho.svg",
                scoreimage: "Joytotheworld_4.png",
                filename:"joy_to_the_world_tamborim",
            },
            {
                id:5,
                trackimg:"pandeireta.png",
                scoreimage: "Joytotheworld_5.png",
                filename:"joy_to_the_world_xilofone",
            },
            {
                id:6,
                trackimg:"jogo_de_sinos.png",
                scoreimage: "Joytotheworld_6.png",
                filename:"joy_to_the_world_jogo_de_sinos",
            },
            {
                id:7,
                trackimg:"ferrinhos.png",
                scoreimage: "Joytotheworld_7.png",
                filename:"joy_to_the_world_triangulo",
            },
        ],
    },
    {
        name: "When the saints go marching in",
        level: 2,
        positioninlevel: 9,
        path: "when_the_saints_go_marching_in",
        author: "",
        scoreimagesize:1540,
        totalstartingperiod:5,
        duration:56,
        bpm:88,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:27.5, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "when_the_saints.png",
                filename:"when_the_saints_go_marching_in_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "when_the_saints.png",
                filename:"when_the_saints_go_marching_in_flauta",
            },
        ],
    },
    {
        name: "Kumbaya",
        level: 2,
        positioninlevel: 10,
        path: "kumbaya",
        author: "",
        scoreimagesize:2880,
        totalstartingperiod:4.5,
        duration:87,
        bpm:74,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:33, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "Kumbaya.png",
                filename:"kumbaya_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "Kumbaya.png",
                filename:"kumbaya_flauta",
            },
        ],
    },
    {
        name: "Winter wonderland",
        level: 2,
        positioninlevel: 11,
        path: "winter_wonderland",
        author: "",
        scoreimagesize:3010,
        totalstartingperiod:9.5,
        duration:90,
        bpm:172,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:29, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:48, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:128, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "winter_wonderland.png",
                filename:"winter_wonderland_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "winter_wonderland.png",
                filename:"winter_wonderland_flauta",
            },
        ],
    },

    {
        name: "À volta da fogueira",
        level: 3,
        positioninlevel: 2,
        path: "a_volta_da_fogueira",
        author: "",
        scoreimagesize:1230,
        totalstartingperiod:5.5,
        duration:61,
        bpm:80,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:30, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "avoltadafogueira_branco-01.png",
                filename:"a_volta_da_fogueira_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "avoltadafogueira_1.png",
                filename:"a_volta_da_fogueira_flauta",
            },
            {
                id:3,
                name:"",
                trackimg:"xilofone.png",
                scoreimage: "avoltadafogueira_3.png",
                filename:"a_volta_da_fogueira_xilofone",
            },
            {
                id:4,
                name:"",
                trackimg:"jogo_de_sinos.png",
                scoreimage: "avoltadafogueira_2.png",
                filename:"a_volta_da_fogueira_jogo_de_sinos",
            },
        ],
    },
    {
        name: "Amazing Grace",
        level: 3,
        positioninlevel: 5,
        path: "amazing_grace",
        author: "",
        scoreimagesize:2160,
        totalstartingperiod:7.5,
        duration:89,
        bpm:72,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:29, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "amazing_grace_branco.png",
                filename:"amazing_grace_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "amazing_grace.png",
                filename:"amazing_grace_flauta",
            },
        ],
    },
    {
        name: "Dois barris em Avis",
        level: 3,
        positioninlevel: 1,
        path: "dois_barris_em_avis",
        author: "",
        scoreimagesize:4620,
        totalstartingperiod:10.5,
        duration:147,
        bpm:90,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:34, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:55, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:76.5, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:98, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "dois_barris.png",
                filename:"dois_barris_em_avis_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "dois_barris.png",
                filename:"dois_barris_em_avis_flauta",
            },
            {
                id:3,
                name:"",
                trackimg:"voz.png",
                scoreimage: "dois_barris.svg",
                filename:"dois_barris_em_avis_voz",
            },
        ],
    },
    {
        name: "Hino da Eurovisão",
        level: 3,
        positioninlevel: 3,
        path: "hino_da_eurovisao",
        author: "",
        scoreimagesize:1550,
        totalstartingperiod:4.5,
        duration:50,
        bpm:72,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:25, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "hino_da_eurovisao.png",
                filename:"hino_da_eurovisao_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "hino_da_eurovisao.png",
                filename:"hino_da_eurovisao_flauta",
            },
        ],
    },
    {
        name: "Longe do Mundo",
        level: 3,
        positioninlevel: 4,
        path: "longe_do_mundo",
        author: "",
        scoreimagesize:2260,
        totalstartingperiod:9,
        duration:84,
        bpm:103,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:29, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "longe_do_mundo.png",
                filename:"longe_do_mundo_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "longe_do_mundo.png",
                filename:"longe_do_mundo_flauta",
            },
        ],
    },

    {
        name: "Blowing in the wind",
        level: 4,
        positioninlevel: 5,
        path: "blowing_in_the_wind",
        author: "",
        scoreimagesize:4420,
        totalstartingperiod:5,
        duration:117,
        bpm:103,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:28, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:60, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:81, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "blowing_in_the_wind.svg",
                filename:"blowing_in_the_wind_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "blowing_in_the_wind.svg",
                filename:"blowing_in_the_wind_flauta",
            },
        ],
    },
    {
        name: "Canção",
        level: 4,
        positioninlevel: 1,
        path: "cancao",
        author: "",
        scoreimagesize:4950,
        totalstartingperiod:9.7,
        duration:105,
        bpm:100,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:20, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:60, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:81, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "cancao.svg",
                filename:"cancao_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"voz.png",
                scoreimage: "cancao.svg",
                filename:"cancao_voz",
            },
            {
                id:3,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "cancao.svg",
                filename:"cancao_flauta",
            },
        ],
    },
    {
        name: "Dó maior e Dó menor",
        level: 4,
        positioninlevel: 3,
        path: "do_maior_e_do_menor",
        author: "",
        scoreimagesize:3000,
        totalstartingperiod:7.5,
        duration:62,
        bpm:75,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:20, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:33, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:46, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "do_maior_e_do_menor.svg",
                filename:"do_maior_e_do_menor_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"voz.png",
                scoreimage: "do_maior_e_do_menor.svg",
                filename:"do_maior_e_do_menor_voz",
            },
            {
                id:3,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "do_maior_e_do_menor.svg",
                filename:"do_maior_e_do_menor_cavaquinho",
            },
        ],
    },
    {
        name: "Mack the knife",
        level: 4,
        positioninlevel: 4,
        path: "mack_the_knife",
        author: "",
        scoreimagesize:2122,
        totalstartingperiod:12.9,
        duration:68,
        bpm:150,
        volume:0.5,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:40, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "mack_the_knife.png",
                filename:"mack_the_knife_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "mack_the_knife.png",
                filename:"mack_the_knife_flauta",
            },
        ],
    },
    {
        name: "Sailing",
        level: 4,
        positioninlevel: 6,
        path: "we_are_sailing",
        author: "",
        scoreimagesize:1440,
        totalstartingperiod:5.5,
        duration:75,
        bpm:63,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:40, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "we_are_sailing_.png",
                filename:"we_are_sailing_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"voz.png",
                scoreimage: "we_are_sailing.png",
                filename:"we_are_sailing_flauta",
            },
        ],
    },
    {
        name: "Suite nº2: Rondó",
        level: 4,
        positioninlevel: 2,
        path: "suite_n2_rondo",
        author: "",
        scoreimagesize:4410,
        totalstartingperiod:2.1,
        duration:91,
        bpm:95,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:25, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:42.5, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:77, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "suite_n2_rondo.svg",
                filename:"suite_n2_rondo_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"voz.png",
                scoreimage: "suite_n2_rondo.svg",
                filename:"suite_n2_rondo_maos",
            },
        ],
    },

    {
        name: "Aura Lee",
        level: 5,
        positioninlevel: 5,
        path: "aura_lee",
        author: "",
        scoreimagesize:1900,
        totalstartingperiod:9.5,
        duration:103,
        bpm:92,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:33, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:54, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:75, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "51_Auralee.svg",
                filename:"aura_lee_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "51_Auralee.svg",
                filename:"aura_lee_flauta",
            },
        ],
    },
    {
        name: "Carnaval de Veneza",
        level: 5,
        positioninlevel: 3,
        path: "carnaval_de_veneza",
        author: "",
        scoreimagesize:2000,
        totalstartingperiod:8.5,
        duration:50,
        bpm:160,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:27, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "CarnavalVeneza.svg",
                filename:"carnaval_de_veneza_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "CarnavalVeneza.svg",
                filename:"carnaval_de_veneza_flauta",
            },
        ],
    },
    {
        name: "Lenda do galo de Barcelos",
        level: 5,
        positioninlevel: 2,
        path: "lenda_do_galo_de_barcelos",
        author: "",
        scoreimagesize:7200,
        totalstartingperiod:11,
        duration:214,
        bpm:110,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:29, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:57, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:110, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:155, color:"rgba(120,120,120,1)"},
            {letter:"5", name:"5ª volta",elapsedtime:174.5, color:"rgba(120,120,120,1)"},
            {letter:"6", name:"6ª volta",elapsedtime:201, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "LendadoGaloBarcelos.svg",
                filename:"lenda_do_galo_de_barcelos_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"voz.png",
                scoreimage: "LendadoGaloBarcelos.svg",
                filename:"lenda_do_galo_de_barcelos_voz",
            },
        ],
    },
    {
        name: "Melodia e harmonia",
        level: 5,
        positioninlevel: 1,
        path: "melodia_e_harmonia",
        author: "",
        scoreimagesize:3250,
        totalstartingperiod:9,
        duration:99,
        bpm:100,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:29, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:57, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:110, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:155, color:"rgba(120,120,120,1)"},
            {letter:"5", name:"5ª volta",elapsedtime:174.5, color:"rgba(120,120,120,1)"},
            {letter:"6", name:"6ª volta",elapsedtime:201, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "MelodiaHarmonia_1.svg",
                filename:"melodia_e_harmonia_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"voz.png",
                scoreimage: "MelodiaHarmonia_2.svg",
                filename:"melodia_e_harmonia_voz",
            },
            {
                id:3,
                name:"",
                trackimg:"voz.png",
                scoreimage: "MelodiaHarmonia_3.svg",
                filename:"",
            },
            {
                id:4,
                name:"",
                trackimg:"voz.png",
                scoreimage: "MelodiaHarmonia_4.svg",
                filename:"",
            },
        ],
    },
    {
        name: "Os olhos da Marianita",
        level: 5,
        positioninlevel: 4,
        path: "os_olhos_da_marianita",
        author: "",
        scoreimagesize:2900,
        totalstartingperiod:4.5,
        duration:106,
        bpm:80,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:29, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:57, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:110, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:155, color:"rgba(120,120,120,1)"},
            {letter:"5", name:"5ª volta",elapsedtime:174.5, color:"rgba(120,120,120,1)"},
            {letter:"6", name:"6ª volta",elapsedtime:201, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "Osolhosdamarianita.svg",
                filename:"os_olhos_da_marianita_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "Osolhosdamarianita.svg",
                filename:"os_olhos_da_marianita_flauta",
            },
        ],
    },

    {
        name: "Ay, linda amiga",
        level: 6,
        positioninlevel: 6,
        path: "ay_linda_amiga",
        author: "",
        scoreimagesize:2310,
        totalstartingperiod:7.1,
        duration:97,
        bpm:60,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:49, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "Aylindaamiga.svg",
                filename:"ay_linda_amiga_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "Aylindaamiga.svg",
                filename:"ay_linda_amiga_flauta",
            },
        ],
    },
    {
        name: "Brincadeiras em terceiras",
        level: 6,
        positioninlevel: 1,
        path: "brincadeiras_em_terceiras",
        author: "",
        scoreimagesize:3500,
        totalstartingperiod:9,
        duration:136,
        bpm:90,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:49, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "Brincadeirasemterceiras.svg",
                filename:"brincadeiras_em_terceiras_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"voz.png",
                scoreimage: "Brincadeirasemterceiras.svg",
                filename:"brincadeiras_em_terceiras_voz",
            },
        ],
    },
    {
        name: "Chegou a hora do adeus",
        level: 6,
        positioninlevel: 6,
        path: "chegou_a_hora_do_adeus",
        author: "",
        scoreimagesize:3500,
        totalstartingperiod:4.5,
        duration:103,
        bpm:90,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:49, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "Chegouahoradoadeus.svg",
                filename:"chegou_a_hora_do_adeus_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"voz.png",
                scoreimage: "Chegouahoradoadeus.svg",
                filename:"chegou_a_hora_do_adeus_flauta",
            },
        ],
    },
    {
        name: "Ciao, ciao, bambina",
        level: 6,
        positioninlevel: 5,
        path: "ciao_ciao_bambina",
        author: "",
        scoreimagesize:1510,
        totalstartingperiod:6,
        duration:80,
        bpm:118,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:27, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:41, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "Ciaociaobambina.svg",
                filename:"ciao_ciao_bambina_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"voz.png",
                scoreimage: "Ciaociaobambina.svg",
                filename:"ciao_ciao_bambina_flauta",
            },
        ],
    },
    {
        name: "Música, obrigado!",
        level: 6,
        positioninlevel: 4,
        path: "musica_obrigado",
        author: "",
        scoreimagesize:7300,
        totalstartingperiod:4.5,
        duration:218,
        bpm:100,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:35, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:42.5, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:78, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:106, color:"rgba(120,120,120,1)"},
            {letter:"5", name:"5ª volta",elapsedtime:114.5, color:"rgba(120,120,120,1)"},
            {letter:"6", name:"6ª volta",elapsedtime:150, color:"rgba(120,120,120,1)"},
            {letter:"7", name:"7ª volta",elapsedtime:169.5, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"Instrumental",
                trackimg:"",
                scoreimage: "musica_obrigado.svg",
                filename:"musica_obrigado_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"voz.png",
                scoreimage: "musica_obrigado.svg",
                filename:"musica_obrigado_voz",
            },
            {
                id:3,
                name:"Silvie",
                trackimg:"voz.png",
                scoreimage: "natalbranco_corrido.png",
                filename:"silvie",
            },
        ],
    },
    {
        name: "Neste Dia da Criança",
        level: 6,
        positioninlevel: 2,
        path: "neste_dia_da_crianca",
        author: "",
        scoreimagesize:7500,
        totalstartingperiod:9.5,
        duration:125,
        bpm:105,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:29.5, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:47.5, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:66.5, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:84, color:"rgba(120,120,120,1)"},
            {letter:"5", name:"5ª volta",elapsedtime:102, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"cd.svg",
                scoreimage: "54_NesteDiadaCrianca.svg",
                filename:"neste_dia_da_crianca_instrumental",
            },
            {
                id:2,
                name:"",
                trackimg:"voz.png",
                scoreimage: "54_NesteDiadaCrianca.svg",
                filename:"neste_dia_da_crianca_voz",
            },
        ],
    },
    {
        name: "Vento Suão",
        level: 6,
        positioninlevel: 3,
        path: "vento_suao",
        author: "",
        scoreimagesize:3900,
        totalstartingperiod:33,
        duration:142,
        bpm:57,
        volume:1,
        marks:[
            //{letter:"", name:"Início",elapsedtime:0, color:"rgba(0,0,0,0.5)"},
            {letter:"1", name:"1ª volta",elapsedtime:29.5, color:"rgba(120,120,120,1)"},
            {letter:"2", name:"2ª volta",elapsedtime:47.5, color:"rgba(120,120,120,1)"},
            {letter:"3", name:"3ª volta",elapsedtime:66.5, color:"rgba(120,120,120,1)"},
            {letter:"4", name:"4ª volta",elapsedtime:84, color:"rgba(120,120,120,1)"},
            //{letter:"", name:"Fim",elapsedtime:141, color:"rgba(0,0,0,0.5)"},
            ],
        tracks:[
            {
                id:1,
                name:"",
                trackimg:"flauta.png",
                scoreimage: "vento_suao_1.png",
                filename:"flauta",
            },
            {
                id:2,
                name:"",
                trackimg:"xilofone.png",
                scoreimage: "vento_suao_2.png",
                filename:"instrumental",
            },
            {
                id:3,
                name:"",
                trackimg:"jogo_de_sinos.png",
                scoreimage: "vento_suao_3.png",
                filename:"xilofone",
            },
            {
                id:4,
                name:"",
                trackimg:"jogo_de_sinos.png",
                scoreimage: "vento_suao_4.png",
                filename:"xilofone_2",
            },
        ],
    },
];






class KaraokeInstr {

    @observable musics;


    constructor() {
        this.musics = initialStore;
    }

    @action setMusic = (newMusic:music) => {
        this.musics.push(newMusic);
    }

    @action getMusic = (name) => {
        return this.musics.filter((i)=>{return i.name==name});
    }

}

const karaokeInstr = new KaraokeInstr();

export default karaokeInstr;
export { KaraokeInstr };
